import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
        <div className="my-6 mt-[100px] bg-white">{children}</div>

        <footer className="m-6 z-20 w-vh p-4 bg-white border-t border-gray-200 shadow-sm flex items-center justify-center text-center">
          <span className="text-sm">
            © 2025{" "}
            <Link href={"/"} className="hover:underline">
              Bloogie™
            </Link>
            . All Rights Reserved.
          </span>
        </footer>
      </body>
    </html>
  );
}
