import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
        <div className="border m-6 bg-white border-gray-200 rounded-2xl">
          {children}
        </div>

        <footer className="m-6 z-20 w-vh p-4 bg-white border-t border-gray-200 shadow-sm flex items-center justify-center text-center">
          <span className="text-sm">
            © 2025{" "}
            <a href="/" className="hover:underline">
              Bloogie™
            </a>
            . All Rights Reserved.
          </span>
        </footer>
      </body>
    </html>
  );
}
